apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: vllm-route
  namespace: default
spec:
  parentRefs:
  - name: example-gateway
  rules:
  - matches:
    - headers:
      - name: target-pod
        value: vllm-0
    backendRefs:
    - name: vllm-0
      port: 8000
      kind: Service
  - matches:
    - headers:
      - name: target-pod
        value: vllm-1
    backendRefs:
    - name: vllm-1
      port: 8000
      kind: Service
  - matches:
    - headers:
      - name: target-pod
        value: vllm-2
    backendRefs:
    - name: vllm-2
      port: 8000
      kind: Service
  - backendRefs:
    - name: vllm-0
      port: 8000
      kind: Service