---
apiVersion: v1
kind: Service
metadata:
  name: vllm-0
  namespace: default
spec:
  ports:
    - port: 8000
      targetPort: 8000
  selector:
    app: vllm-0
---
apiVersion: v1
kind: Service
metadata:
  name: vllm-1
  namespace: default
spec:
  ports:
    - port: 8000
      targetPort: 8000
  selector:
    app: vllm-1
---
apiVersion: v1
kind: Service
metadata:
  name: vllm-2
  namespace: default
spec:
  ports:
    - port: 8000
      targetPort: 8000
  selector:
    app: vllm-2